/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// Java Standard Library
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

// Apache Commons IO
import org.apache.commons.io.FileUtils;

// Apache Commons Lang
import org.apache.commons.lang3.StringUtils;

// PDFBox
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

// ASCII Render
import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.elements.PseudoText;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        App app = new App();

        System.out.println(app.getGreeting());
        System.out.println();

        System.out.println("=== ASCII Render ===");
        app.asciiRender();
        System.out.println();

        System.out.println("=== PDFBox ===");
        app.pdfBox();
        System.out.println("PDF created: pdfBox.pdf");
        System.out.println();

        System.out.println("=== String Utilities ===");
        app.stringUtilities("Hello World");
        System.out.println();

        System.out.println("=== Datei Utility ===");
        app.dateiUtility();
        System.out.println();
    }


    public void asciiRender() {
        IRender render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(120).height(20);
        builder.element(new PseudoText("PseudoText"));
        ICanvas canvas = render.render(builder.build());
        String s = canvas.getText();
        System.out.println(s);
    }

    public void pdfBox() throws IOException {
        // PDF Box
        PDDocument helloPdf = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        helloPdf.addPage(page);
        PDPageContentStream contentStream = new PDPageContentStream(helloPdf, page);
        contentStream.beginText();
        contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 36);
        contentStream.newLineAtOffset(5, 400);
        contentStream.showText("Hello DevOps!!!");
        contentStream.endText();
        contentStream.close();
        helloPdf.save(new File("pdfBox.pdf"));
        helloPdf.close();
    }

    public void stringUtilities(String input) {
        String capitalized = StringUtils.capitalize(input);
        System.out.println("Capitalized: " + capitalized);
    }

    public void dateiUtility() throws IOException {
        File file = new File("dateiUtility.txt");

        // Datei schreiben
        FileUtils.writeStringToFile(file, "Hallo Gradle!", StandardCharsets.UTF_8);

        // Datei lesen
        String content = FileUtils.readFileToString(file, StandardCharsets.UTF_8);
        System.out.println("File content: " + content);
    }
}
