pipeline {
    agent any
    environment {
        JAVA_HOME = "/opt/jdks/jdk-25"
    }
    stages {
        stage('Checkout') { 
            steps {
                sh 'echo checkout'
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[
                    // credentialsId: 'GitHub-mosazhaw', 
                    url: 'https://github.com/CarlsonBuma/zhaw-devops.git'
                ]])
            }
        }
        stage('Build') { 
            steps {
                sh 'echo build'
                dir('devops-03-demo/backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'    
                }
                recordCoverage(tools: [[parser: 'JACOCO',pattern: '**/jacocoTestReport.xml']])
                junit stdioRetention: '', testResults: '**/test-results/test/*.xml'
                nodejs('24.11.1') {
                    dir('devops-03-demo/frontend') {
                        sh 'npm install'
                        sh 'npm run lint:html'                    
                    }
                }
                withCredentials([string(credentialsId: '28a9f636-a2c0-4ac7-a0d0-589d35361d65', variable: 'TOKEN')]) {
                    dir('devops-03-demo/backend') {
                        sh './gradlew sonar -Dsonar.projectKey=devops-backend -Dsonar.projectName=\'devops-backend\' -Dsonar.host.url=http://sonarqube:9000 -Dsonar.token=$TOKEN'    
                    }                    
                }
                withCredentials([string(credentialsId: '198176b2-203f-4909-a3b0-6f05c6198970', variable: 'TOKEN')]) {
                    dir('devops-03-demo/frontend') {
                        nodejs('24.11.1') {
                            sh 'npx sonar-scanner -Dsonar.host.url=http://sonarqube:9000 -Dsonar.projectKey=devops-frontend -Dsonar.projectName=\'devops-frontend\' -Dsonar.token=$TOKEN'    
                        }
                    }                    
                }
            }
        }
        stage('Docker') {
            steps {
                sh '''
                    cd devops-03-demo
                    export DOCKER_HOST=tcp://host.docker.internal:2375
                    docker build -t carlson/devopsdemo .
                '''
            }
        }
    }
}

