pipeline {
    agent any
    environment {
        JAVA_HOME = "/opt/jdks/jdk-25"
    }
    stages {
        stage('Checkout') { 
            steps {
                sh 'echo checkout'
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[
                    // credentialsId: 'GitHub-mosazhaw', 
                    url: 'https://github.com/CarlsonBuma/zhaw-devops.git'
                ]])
            }
        }
        stage('Build') { 
            steps {
                sh 'echo build'
                dir('devops-03-demo/backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'    
                }
                recordCoverage(
                    tools: [[
                        parser: 'JACOCO',
                        pattern: 'devops-03-demo/backend/build/reports/jacoco/test/jacocoTestReport.xml'
                    ]],
                    sourceDirectories: [[
                        path: 'devops-03-demo/backend/src/main/java'
                    ]]
                )
                junit stdioRetention: '', testResults: 'devops-03-demo/backend/build/test-results/test/*.xml'
                nodejs('Node 24.11.1') {
                    dir('devops-03-demo/frontend') {
                        sh 'npm install'
                        sh 'npm run lint:html'
                        sh 'npm run test-local-chrome'                    
                    }
                }
                withCredentials([string(credentialsId: 'sonar-secret-backend', variable: 'TOKEN')]) {
                    dir('devops-03-demo/backend') {
                        sh './gradlew sonar -Dsonar.projectKey=devops-backend -Dsonar.projectName=\'devops-backend\' -Dsonar.host.url=http://sonarqube:9000 -Dsonar.token=$TOKEN'    
                    }                    
                }
                withCredentials([string(credentialsId: 'sonar-secret-frontend', variable: 'TOKEN')]) {
                    dir('devops-03-demo/frontend') {
                        nodejs('Node 24.11.1') {
                            sh 'npx sonar-scanner -Dsonar.host.url=http://sonarqube:9000 -Dsonar.projectKey=devops-frontend -Dsonar.projectName=\'devops-frontend\' -Dsonar.token=$TOKEN'    
                        }
                    }                    
                }
            }
        }
        stage('Docker') {
            steps {
                sh '''
                    cd devops-03-demo
                    export DOCKER_HOST=tcp://host.docker.internal:2375
                    docker build -t carlson/devopsdemo .
                '''
            }
        }
    }
}

