pipeline {
    agent any
    environment {
        JAVA_HOME = "/opt/jdks/jdk-25"
    }
    stages {
        stage('Checkout') { 
            steps {
                sh 'echo checkout'
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[
                    // credentialsId: 'GitHub-mosazhaw', 
                    url: 'https://github.com/CarlsonBuma/zhaw-devops.git'
                ]])
            }
        }
        stage('Build') { 
            steps {
                sh 'echo build'
                dir('devops-03-demo/backend') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew test'    
                }
                recordCoverage(
                    tools: [[
                        parser: 'JACOCO',
                        pattern: 'devops-03-demo/backend/build/reports/jacoco/test/jacocoTestReport.xml'
                    ]],
                    sourceDirectories: [[
                        path: 'devops-03-demo/backend/src/main/java'
                    ]]
                )
                junit stdioRetention: '', testResults: 'devops-03-demo/backend/build/test-results/test/*.xml'
                nodejs('Node 24.11.1') {
                    dir('devops-03-demo/frontend') {
                        sh 'npm install'
                        sh 'npm run lint:html'                  
                    }
                }
                withCredentials([string(credentialsId: 'sonar-secret-backend', variable: 'TOKEN')]) {
                    dir('devops-03-demo/backend') {
                        sh './gradlew sonar -Dsonar.projectKey=devops-backend -Dsonar.projectName=\'devops-backend\' -Dsonar.host.url=http://sonarqube:9000 -Dsonar.token=$TOKEN'    
                    }                    
                }
                withCredentials([string(credentialsId: 'sonar-secret-frontend', variable: 'TOKEN')]) {
                    dir('devops-03-demo/frontend') {
                        nodejs('Node 24.11.1') {
                            sh 'npx sonar-scanner -Dsonar.host.url=http://sonarqube:9000 -Dsonar.projectKey=devops-frontend -Dsonar.projectName=\'devops-frontend\' -Dsonar.token=$TOKEN'    
                        }
                    }                    
                }
            }
        }
        stage('Docker-Build-Image') {
            steps {
                sh '''
                    export DOCKER_HOST=tcp://host.docker.internal:2375
                    cd devops-03-demo
                    docker build -t carlsonpatrick/devops-demo-app .
                '''
            }
        }
        stage('Docker-Run-Container') {
            steps {
                sh '''
                    export DOCKER_HOST=tcp://host.docker.internal:2375

                    docker rm -f devops-docker-demo-app || true

                    docker run -d \
                        --name devops-docker-demo-app \
                        -p 8080:8080 \
                        --restart unless-stopped \
                        carlsonpatrick/devops-demo-app
                '''
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'devops-ammanpa4', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh '''
                            export DOCKER_HOST=tcp://host.docker.internal:2375
                            docker login -u $USERNAME -p $PASSWORD
                            docker push carlsonpatrick/devops-demo-app
                        '''
                    }
                }
            }
        }

        stage('Trigger Render Deployment') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'devops-render-docker', variable: 'KEY')]) {
                        sh "curl https://api.render.com/deploy/$KEY"
                    }
                }
            }
        } 
    }
}

